name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.12.2'

      - name: Corepack enable
        run: corepack enable
  
      - name: Check yarn version
        run: yarn -v

      - name: Install deps
        run: yarn
    
      - name: Run build
        run: yarn build
        env:
          NODE_ENV: development
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_APP_VERSION: ${{ github.sha }}

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './dist/**'
          target: ${{ secrets.DEV_BUILD_TARGET_LOCATION }}